# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: 'Nobuto Murata' # Website name
baseurl: 'https://nobuto-m.github.io/' # Website URL

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    #- path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify-cms
    #- path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-reveal
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5

############################
## ADVANCED
############################

# NOTE: it doesn't work with submodule actually
# https://github.com/gohugoio/hugo/issues/5533
enableGitInfo: true
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
  post: 'post/:year/:slug/'
  year: 'post/:slug/'
# rely on a client-side redirection
disableAliases: false
outputs:
  # home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  # don't generate webmanifest, Netlify headers and redirects
  home: [HTML, RSS, JSON]
  section: [HTML, RSS]
  # suppress unnecessary RSS
  taxonomy: [HTML]
# You have configured output formats for 'taxonomy' in your site
# configuration. In Hugo 0.73.0 we fixed these to be what most people
# expect (taxonomy and term). But this also means that your site
# configuration may not do what you expect.
ignoreErrors: ["error-output-taxonomy"]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
  # for yearly archives of posts
  year: year
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
privacy:
  twitter:
    enableDNT: true
